# -*- coding: utf-8 -*-
"""Data Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLYJMLJ6ZZLKHrIFy0KiNcr6A5nKNco8
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# Settings
rows = 1000
countries = ['USA', 'Netherlands', 'France', 'India', 'Malaysia', 'Germany', 'Spain', 'Sweden', 'UAE', 'UK', 'Canada', 'Japan']
grades = ['Raw/Unrefined', 'Refined (Grade A)', 'Fractionated', 'Organic Certified']
channels = ['B2B', 'Wholesale', 'Direct-to-Consumer', 'Industrial']

data = []
start_date = datetime(2024, 1, 1)

for i in range(rows):
    date = start_date + timedelta(days=random.randint(0, 800))
    country = random.choice(countries)
    grade = random.choice(grades)
    channel = random.choice(channels)

    # Logic: Organic and Refined are more expensive
    base_price = 1100 if grade in ['Organic Certified', 'Refined (Grade A)'] else 850
    unit_price = base_price + random.randint(-150, 150)

    # Logic: Large volume gets slight discount
    quantity = random.randint(500, 50000)
    cost_per_kg = unit_price * random.uniform(0.70, 0.85) # 15-30% margin

    revenue = quantity * unit_price
    total_cost = quantity * cost_per_kg
    profit = revenue - total_cost

    data.append([date, f"TXN-{1000+i}", country, grade, channel, unit_price, quantity, revenue, total_cost, profit])

df = pd.DataFrame(data, columns=['Date', 'Transaction_ID', 'Country', 'Grade', 'Channel', 'Price_Per_KG', 'Qty_KG', 'Revenue', 'Total_Cost', 'Profit'])
df.to_csv('Shea_Butter_Big_Data.csv', index=False)
print("File Generated: Shea_Butter_Big_Data.csv with 1,000 rows.")